Message.create(text: "Hello, world!")
Message.create(text: "How are you today?")
Message.create(text: "Have a great day!")
Message.create(text: "You're amazing!")
Message.create(text: "You're the best!")
Message.create(text: "We're glad to see you again!")